version: "3.7"

services:
  app_front:
    build:
      context: .
      dockerfile: conf/dockerfile/front.dockerfile
    container_name: "symfony"
    hostname: localhost
    entrypoint: ["tail", "-f", "/dev/null"] #to keep it running
    ports:
      - "80:80"
      - "443:443"
    links:
      - "db_symfony:mysql-symfony"
    volumes:
      - ./app/:/home/symfo
    depends_on:
      - db_symfony
    environment:
      - SYMFONY_DB_HOST=db_symfony
  db_symfony:
    image: mysql:8
    container_name: db_symfony
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-symfony:/var/lib/mysql-symfony
      - ./conf/mysql/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfo

  db-pma-symfo:
    image: "phpmyadmin/phpmyadmin"
    container_name: "db-pma-symfo"
    links:
      - "db_symfony:mysql-symfony"
    ports:
      - "10001:80"
    depends_on:
      - db_symfony
    environment:
      - PMA_HOSTS=db_symfony

volumes:
  mysql-symfony:
